### ISSUE TITLE
Login screen for online mode

### ISSUE THREAD

**Issue by puerto-hub** [DIT112-V21/group-04#56]
### User Story
As a medical worker, I want to be able to login to an external server within the app so that the connection to an external server cannot be accessed by unauthorized users.

### Acceptance Criteria
- After selecting “Online mode” on the server selection screen in the app, a login prompt should be displayed.
- Upon successful login, the user should be sent to the car selection screen.

**Comment by MarkusJ299** [comment]
Closing this issue. It is out of scope due to time constraints.
